const question = document.getElementById("question");
const choices = Array.from(document.getElementsByClassName("choice-text"));
const progressText = document.getElementById("progressText");
const scoreText = document.getElementById("score");
const progressBarFull = document.getElementById("progressBarFull");
const quizname = document.getElementById("quizname");
//mod here to match the SAR66 Topic content

let currentQuestion = {};
let acceptingAnswers = false;
let score = 0;
let questionCounter = 0;
let availableQuesions = [];
//set your questions here
let questions = [
  {question: "Lighting strike damage on aircraft skin is usually seen in the form of:",
choice1: "scorch marks or pitting.",
choice2: "small circular holes.",
choice3: "jagged tears.",
answer: 1},
{question: "Select the correct statement with regards to torque loading.",
choice1: "Threads of bolts and nuts must be lubricated.",
choice2: "Total torque = friction drag torque + desired torque.",
choice3: "To align the castle nut, a 10% increase in torque is acceptable.",
answer: 2},
{question: "Zinc chromate primer controls corrosion by:",
choice1: "releasing chromate ions on to the surface of the metal.",
choice2: "completely excluding water from the base metal.",
choice3: "reacting with the aluminum to form a protective chrome-aluminum plating.",
answer: 2},
{question: "Which of the following NDT methods is applicable for detecting moisture in honeycomb core components?",
choice1: "X-ray",
choice2: "Eddy current",
choice3: "Ultrasonic",
answer: 1},
{question: "Aircraft spare parts in a quarantine store:",
choice1: "may be fitted to an aircraft in urgent situations.",
choice2: "must always be disposed of.",
choice3: "must not be fitted to an aircraft.",
answer: 3},
{question: "A liquid NDT penetrant that is not water soluble or post-emulsifying would commonly be known as:",
choice1: "a solvent removable penetrant.",
choice2: "a solvent immersible penetrant.",
choice3: "an air-dry penetrant.",
answer: 1},
{question: "The amount of current a wire is capable of carrying is determined by its:",
choice1: "insulation.",
choice2: "length.",
choice3: "cross-sectional area.",
answer: 3},
{question: "Which of the following NDT method is most suitable for use on a steel part?",
choice1: "Magnetic particle inspection",
choice2: "Penetrant inspection (dye-check)",
choice3: "Eddy current inspection",
answer: 1},
{question: "It is highly dangerous to operate the halves of pressurised ____ cylinders with greasy hands.",
choice1: "nitrogen",
choice2: "oxygen",
choice3: "acetylene",
answer: 2},
{question: "On large transport aircraft, the location of the centre of gravity is normally expressed as a percentage of the:",
choice1: "mean aerodynamic chord (MAC).",
choice2: "datum arm.",
choice3: "aircraft length.",
answer: 1},
{question: "To locate faults in the aircraft wiring, one should refer to the:",
choice1: "wiring diagram manual.",
choice2: "maintenance manual.",
choice3: "component location diagram manual.",
answer: 1},
{question: "When refuelling from a hydrant cart containing Jet A-1 fuel, the decal markings on the cart should be coloured:",
choice1: "red with white lettering.",
choice2: "blue with white lettering.",
choice3: "black with white lettering.",
answer: 1},
{question: "The two types of orthographic projections are:",
choice1: "1st and 2nd angle.",
choice2: "1st and 3rd angle.",
choice3: "isometric and oblique.",
answer: 2},
{question: "A piece of metal structure has surface pitting and etching covered with a grey or white powdery deposit. Based on this evidence you would consider that the metal is:",
choice1: "aluminium alloy or magnesium.",
choice2: "copper or copper alloy.",
choice3: "iron or steel.",
answer: 1},
{question: "A moving coil measuring instrument may be used with:",
choice1: "both AC and DC supplies.",
choice2: "an AC supply only.",
choice3: "a DC supply only.",
answer: 1},
{question: "In relation to fits and limits, maximum allowance is the difference between the:",
choice1: "largest shaft and the smallest hole.",
choice2: "upper limits and lower limit.",
choice3: "smallest shaft and the largest hole.",
answer: 3},
{question: "Information that provides the means to troubleshoot a fault as far as replaceable module level only is found in a:",
choice1: "block diagram.",
choice2: "location diagram.",
choice3: "wiring diagram.",
answer: 1},
{question: "When an electric power tool has two wires in the power cord, there is a danger that:",
choice1: "insufficient current may be available, which will cause an internal short.",
choice2: "if the power lead becomes shorted to the motor case, power will flow to ground through the operator’s body.",
choice3: "an internal short may occur if the load on the electric motor exceeds specifications.",
answer: 2},
{question: "Holes for special structural fasteners are normally drilled:",
choice1: "oversize.",
choice2: "for a running fit.",
choice3: "for a close tolerance fit.",
answer: 3},
{question: "In order to relate the percentage MAC (mean aerodynamic chord) to the datum, the weight and balance information must include:",
choice1: "the length of MAC in inches and overall length of the aircraft.",
choice2: "the length of the datum to the leading edge of MAC and the overall length of the aircraft.",
choice3: "the length of MAC in inches and the location of the leading edge of MAC in inches from the datum.",
answer: 3},
{question: "When making up an electrical connector, unused holes:",
choice1: "should be fitted with filler plug.",
choice2: "should be fitted with connector pins.",
choice3: "should be left as they are.",
answer: 1},
{question: "When using ohmmeters, the first thing that must be done is to:",
choice1: "replaced the battery.",
choice2: "short the terminals together and adjust the indication for zero.",
choice3: "short the terminals together and adjust the indication for infinity.",
answer: 2},
{question: "The significant of the ‘60’ used in 60-40 solder is the:",
choice1: "tin content.",
choice2: "zinc content.",
choice3: "lead content.",
answer: 1},
{question: "The standard antenna used in field strength measurement is:",
choice1: "fitted with a parabolic reflector.",
choice2: "a one metre-long wire.",
choice3: "a Marconi antenna.",
answer: 1},
{question: "Grease and oil must be kept away from:",
choice1: "nitrogen cylinders.",
choice2: "oxygen cylinders.",
choice3: "carbon dioxide cylinders.",
answer: 2},
{question: "A hygrometer located in a bonded store would be used to measure:",
choice1: "temperature.",
choice2: "pressure.",
choice3: "humidity.",
answer: 3},
{question: "Lighting strikes on aircraft may be evident as damage where the lighting entered the aircraft and is not indicated by:",
choice1: "residual magnetism effecting the compasses.",
choice2: "pitting and/or burning at the wing trailing edge.",
choice3: "small circular holes on the fuselage or wing surfaces.",
answer: 1},
{question: "Sectioning is used on a drawing to:",
choice1: "reveal hidden or inner features of an object.",
choice2: "show how the object is to be assembled.",
choice3: "create an auxiliary view.",
answer: 1},
{question: "When taxiing an aircraft to the ramp, a flashing green light is signalled from the control tower. This would indicate that the aircraft:",
choice1: "may commence taxiing.",
choice2: "must return to the starting point.",
choice3: "must exercise extreme caution.",
answer: 1},
{question: "Information used for electrical troubleshooting that often specifies system components by part number and location is known as a:",
choice1: "pictorial diagram.",
choice2: "wiring diagram.",
choice3: "exploded view drawing.",
answer: 2},
{question: "A clearance fit is one that gives:",
choice1: "a negative allowance.",
choice2: "a positive allowance.",
choice3: "the least interference.",
answer: 3},
{question: "Aircraft tyres should be deflated before:",
choice1: "removing the wheel from the axle.",
choice2: "jacking the wheel clear of the ground.",
choice3: "adjusting undercarriage linkages.",
answer: 1},
{question: "When wires in a wiring loom bundle are spliced, the splices should be:",
choice1: "staggered along the bundle.",
choice2: "grouped together at one point.",
choice3: "group together in pairs along the bundle.",
answer: 1},
{question: "Which one of the following hydraulic fluids is coloured red?",
choice1: "MIL-H-7644",
choice2: "MIL-H-5606",
choice3: "Skydrol LD",
answer: 2},
{question: "To protect “O” ring seals from damage when fitting them over sharp edges, the sharp edges should be covered with:",
choice1: "grease.",
choice2: "system fluid.",
choice3: "plastic tape.",
answer: 3},
{question: "The shelf life of aircraft parts is normally set by the:",
choice1: "Civil Aviation Authority.",
choice2: "storeman.",
choice3: "manufacturer.",
answer: 3},
{question: "A technician troubleshooting an oil leak in a constant speed unit would find the unit’s principles of operation in a:",
choice1: "logic flowchart.",
choice2: "block diagram.",
choice3: "schematic diagram.",
answer: 3},
{question: "Dulling of a metal surface that has been exposed to battery fumes, exhaust gases or salt spray would indicate:",
choice1: "uniform surface corrosion.",
choice2: "filiform corrosion.",
choice3: "galvanic corrosion.",
answer: 1},
{question: "After a metalworking job is completed and a hand file is ready for storage, it should be:",
choice1: "lightly oiled and wrapped in paper or plastic and put in a drawer.",
choice2: "clean and hung on a rack.",
choice3: "coated with a waxed-based inhibiting fluid and stored vertically in tin containing other files.",
answer: 2},
{question: "To increase the range of an ammeter:",
choice1: "a shunt is connected in parallel with the meter.",
choice2: "a shunt is connected in series with the meter.",
choice3: "a multiplier is connected in series with the meter.",
answer: 1},
{question: "To measure the electrical resistance of a fire-bottle squib:",
choice1: "any ohmmeter may be used.",
choice2: "a safety ohmmeter is used.",
choice3: "a megger is used.",
answer: 2},
{question: "When using the magnetic particle method of NDT, cracks at right angles to the axis of a steel rod would be detected using:",
choice1: "longitudinal magnetism.",
choice2: "circular magnetism.",
choice3: "lateral magnetism.",
answer: 2},
{question: "When troubleshooting an electrical circuit using a multimeter, which measurement should only be taken if power is OFF to the circuit?",
choice1: "Voltage",
choice2: "Resistance",
choice3: "Current",
answer: 2},
{question: "Aircraft parts or components that are ready for use on the aircraft are kept in the:",
choice1: "quarantine store.",
choice2: "bonded store.",
choice3: "commercial store.",
answer: 2},
{question: "When comparing soldering and brazing:",
choice1: "silver soldering is a form of brazing.",
choice2: "brazing fuses the metals together while soldering makes a union through capillary action.",
choice3: "silver solder has a lower melting point than tin-lead solder.",
answer: 2},
{question: "Static discharge resulting from a lighting strike is usually visible as:",
choice1: "pitting and burning at the wing trailing edge.",
choice2: "small circular holes on the fuselage and wing surfaces.",
choice3: "blisters on radomes.",
answer: 1},
{question: "If the mercury is spilt in the cargo hold of an aircraft it will have the most damaging affect on structure containing:",
choice1: "aluminium alloy.",
choice2: "titanium.",
choice3: "magnesium.",
answer: 1},
{question: "Which one of the following fits has the largest interference?",
choice1: "Running fit",
choice2: "Push fit",
choice3: "Drive fit",
answer: 1},
{question: "Which methods are suitable for inspecting fastener holes with fasteners installed?",
choice1: "Low frequency eddy current and ultrasonic inspection.",
choice2: "Low frequency eddy current and penetrant inspection.",
choice3: "Low frequency eddy current and magnetic particle inspection.",
answer: 1},
{question: "Aviators breathing oxygen cylinders installed on an aircraft are colour coded:",
choice1: "green.",
choice2: "black.",
choice3: "blue.",
answer: 1},
{question: "The bonding resistance of radio equipment should be no greater than:",
choice1: "0.030 ohms.",
choice2: "0.003 ohms.",
choice3: "0.300 ohms.",
answer: 2},
{question: "If a 25-inch torque wrench fitted with a 5-inch extension shows a dial reading of 100 inch-pounds, the actual torque loading on a bolt is:",
choice1: "80 inch-pounds.",
choice2: "120 inch-pounds.",
choice3: "130 inch-pounds.",
answer: 2},
{question: "The thread on the spindle of an English micrometer has a pitch of:",
choice1: "40 threads per inch, and one complete turn of the thimble will move the spindle 0.025 inch.",
choice2: "50 threads per inch, and one complete turn of the thimble will move the spindle 0.025 inch.",
choice3: "100 threads per inch, and one complete turn of the thimble will move the spindle 0.010 inch.",
answer: 1},
{question: "On an isometric drawing all vertical lines are drawn as verticals and all horizontal lines are drawn at an angle of:",
choice1: "30 degrees.",
choice2: "45 degrees.",
choice3: "60 degrees.",
answer: 1},
{question: "When soft soldering, flux is used to:",
choice1: "prevent oxidation of the metal joint as heat is applied.",
choice2: "confine the solder to the area where it is required.",
choice3: "prevent oxidation of the solder.",
answer: 1},
{question: "Defuelling an aircraft must be carried out:",
choice1: "in a hangar where there is no wind or fire hazards.",
choice2: "outside a hangar where there are no fire hazards.",
choice3: "into clean drums but never straight into a fuel trucks.",
answer: 2},
{question: "An aircraft part having a specified dimension of 1.500 inches and a tolerance of +0.004 inches could be manufactured to a size that is in range:",
choice1: "1.496 inches to 1.504 inches.",
choice2: "1.500 inches to 1.504 inches.",
choice3: "1.496 inches to 1.500 inches.",
answer: 2},
{question: "When no specific torque value is given for an aircraft wheel retaining nut, the nut should be tightened until bearing drag is felt, then backed off by:",
choice1: "1/12th of a turn.",
choice2: "1/8th of a turn.",
choice3: "1/6th of a turn.",
answer: 3},
{question: "The smallest graduated reading on a metric vernier calliper is:",
choice1: "0.5mm.",
choice2: "0.001mm.",
choice3: "0.02mm.",
answer: 3},
{question: "After finding severe skin damage resulting from a lighting strike, all control surfaces should be inspected to check for damage because:",
choice1: "unsatisfactory bonding may have allowed static discharge across hinge bearings causing burning, breakup or seizure.",
choice2: "the mass balance of the control surface may have changed.",
choice3: "the hinge bearings may have become magnetised.",
answer: 1},
{question: "In a SAR145 maintenance organisation, quality assurance standards would be monitored through:",
choice1: "CAAS inspections.",
choice2: "internal audits.",
choice3: "customer complaints.",
answer: 2},
{question: "Whenever disassembling oxygen systems, ensure that hands, clothes and tools are free from:",
choice1: "chalk dust.",
choice2: "oil and grease.",
choice3: "water.",
answer: 2},
{question: "Before using an ohmmeter to check a diode, what diode parameter should be known?",
choice1: "PIV",
choice2: "Maximum current rating",
choice3: "Maximum power rating",
answer: 1},
{question: "A drawing for a round section of shaft that requires a diameter of 0.3125 plus or minus 0.0005 has a:",
choice1: "tolerance of 0.0005.",
choice2: "allowance of 0.001.",
choice3: "tolerance of 0.001.",
answer: 3},
{question: "The freezing-point depressant (FPD) fluid thst is best suited for ground anti-icing of airframe structure is:",
choice1: "type 1.",
choice2: "demineralised water.",
choice3: "type 2.",
answer: 3},
{question: "On engineering drawings that use orthographic projection:",
choice1: "either first or third angle projections are shown.",
choice2: "one side is shown at 45 degrees.",
choice3: "lines are shown at 30 degrees to horizontal.",
answer: 1},
{question: "If lightning strike evidence is found externally on a jet engine cowling. Additional checks should be made specially for:",
choice1: "fan or compressor blade damage.",
choice2: "internal cowling damage.",
choice3: "contamination of engine oil filters and chip detectors.",
answer: 2},
{question: "When installing a close tolerance bolt, the pilot hole for the reamer would normally be drilled:",
choice1: "0.001” to 0.003” smaller than the reamer diameter.",
choice2: "0.009” to 0.012” smaller than the bolt diameter.",
choice3: "0.0001” to 0.0007” smaller than the reamer diameter.",
answer: 1},
{question: "Which of the following types of pilers are often used in aviation for safe wiring?",
choice1: "Needlenose and slip-joint",
choice2: "Roundnose and flatnose",
choice3: "Duckbill and diagonal cutting",
answer: 3},
{question: "The purpose of using flux during soft soldering is:",
choice1: "to prevent oxidation and keep the metal surfaces clean.",
choice2: "to prevent overheating of the solder by improving heat dissipation.",
choice3: "to increase the strength of the joint.",
answer: 1},
{question: "Limits and allowance depend on:",
choice1: "nominal size only.",
choice2: "classification of fit only.",
choice3: "both nominal size and classification of fit.",
answer: 3},
{question: "When tightening a fastener with a torque wrench and an adapter, the torque need not be recalculated if the:",
choice1: "adapter shortens the lever.",
choice2: "adapter acts at a right angle to the lever.",
choice3: "adapter lengthens the lever.",
answer: 2},
{question: "When storing sheets in the bonded store they should:",
choice1: "never be stored on edge.",
choice2: "be kept in cool and dry conditions.",
choice3: "have all protective papers or films removed.",
answer: 2},
{question: "The main disadvantage of utilising X-ray and gamma-ray inspection is:",
choice1: "x and gamma rays pose a radiation hazard so the area must be cleared of personnel during exposure.",
choice2: "x and gamma rays equipment are expensive.",
choice3: "both sides of structure must be accessible.",
answer: 1},
{question: "The breakdown or build-up of a metal surface due to excess friction between two parts, where particles of soft metal are welded to the harder surface, is commonly called:",
choice1: "chaffing.",
choice2: "galling.",
choice3: "burnishing.",
answer: 1},
{question: "If resistance readings are being taken using a multimeter on a energised electrical circuit, the result will be:",
choice1: "higher than normal resistance readings.",
choice2: "normal resistance readings.",
choice3: "probable damage to the multimeter.",
answer: 3},
{question: "An orthographic engineering drawing would have:",
choice1: "angles shown at 60 degrees.",
choice2: "angles shown at 45 degrees.",
choice3: "up to six views.",
answer: 3},
{question: "Where would jacking procedures be found for a particular aircraft?",
choice1: "Maintenance manual",
choice2: "Operator’s manual",
choice3: "Aircraft specification sheet",
answer: 1},
{question: "In order for dye penetrant inspection to be effective, the material being checked must:",
choice1: "have surface cracks.",
choice2: "be non-magnetic.",
choice3: "have subsurface cracks.",
answer: 1},
{question: "If tolerance values are given on either side of the nominal hole dimension, the hole has a:",
choice1: "clearance fit.",
choice2: "unilateral tolerance.",
choice3: "bilateral tolerance.",
answer: 3},
{question: "In regards to fits and limits, the modern limit systems favours the:",
choice1: "hole basis.",
choice2: "shaft basis.",
choice3: "metric system.",
answer: 3},
{question: "Flux is used when soldering joints because:",
choice1: "it unites with oxides in the molten solder and floats them to the surface.",
choice2: "it dissolves surface grease and so improves the bond.",
choice3: "it reacts with the solder to promote more rapid solification.",
answer: 1},
{question: "Before troubleshooting an aircraft system, a technician should first:",
choice1: "functionally check the system for faults.",
choice2: "replace the item or items most likely to be the cause.",
choice3: "review how the system correctly functions.",
answer: 3},
{question: "When using a digital multimeter to look for an open or shorted circuit, you would use the:",
choice1: "continuity test function of the meter.",
choice2: "current test function of the meter.",
choice3: "voltage test function of the meter.",
answer: 1},
{question: "When measuring the bow (hole) in a shaft with a dial test indicator the reading obtained from one revolution of the shaft must:",
choice1: "be doubled.",
choice2: "be halved.",
choice3: "not be changed.",
answer: 3},
{question: "Life rafts and life jackets should be stored in a:",
choice1: "bightly lit room.",
choice2: "warm, dry room.",
choice3: "cool, dry room.",
answer: 3},
{question: "Where a length of copper wire is to be replaced by aluminium wire, the aluminium wire should be:",
choice1: "smaller by two gauge numbers.",
choice2: "larger by two gauge numbers.",
choice3: "of the same gauge number.",
answer: 3},
{question: "Soft solders are those alloys of mainly:",
choice1: "lead and tin.",
choice2: "lead and zinc.",
choice3: "tin and zinc.",
answer: 1},
{question: "When a visual inspection of an aircraft undercarriage finds evidence of static discharge, further inspection may often be carried out to check for:",
choice1: "residual static electricity.",
choice2: "residual magnetism.",
choice3: "low undercarriage strut pressure.",
answer: 2},
{question: "Prior to carrying out a bonding test, a check should be made on the state of the nickel-alkaline cell of the bonding tester by observing that:",
choice1: "the meter reads full-scale when the two spikes of the 6-foot cable probe are shorted by the single spike of the 60-foot probe.",
choice2: "the meter reads zero when the two spikes of the 6-foot cable probes are shorted by a suitable conductor.",
choice3: "a full-scale deflection of the meter is obtained when the two spikes of the 6-foot cable probe are shorted by a suitable conductor.",
answer: 3},
{question: "Select the correct statement regarding storage of compressed gas-cylinders.",
choice1: "Breathing oxygen and welding oxygen cylinders are interchangeable.",
choice2: "Acetylene cylinders should always be stored in the upright position.",
choice3: "Oxygen cylinders are protected with inhibiting oil.",
answer: 2},
{question: "Unless otherwise specified, when assembling components using nuts and bolts, the bolt is fitted:",
choice1: "head forwards, inboard or upwards.",
choice2: "nut forwards, inboard or upwards.",
choice3: "in the direction that is least likely to damage the component or bolt on installation.",
answer: 3},
{question: "On a large aircraft, which one of the following devices would most likely contain hazardous radiation material?",
choice1: "A line replaceable unit in the avionics services bay.",
choice2: "A luminescent exit sign.",
choice3: "Built in test equipment.",
answer: 2},
{question: "What level of knowledge is the most useful for a technician troubleshooting an engine fuel pressure fault?",
choice1: "In-depth knowledge of the aircraft’s fuel pressure indicator.",
choice2: "General knowledge of the aircraft’s complete fuel system and components.",
choice3: "In-depth knowledge of the engine type and its systems.",
answer: 2},
{question: "Lightning strike is often associated with other abnormal occurrences such as:",
choice1: "heavy landings.",
choice2: "flight through turbulence.",
choice3: "smoke in the cockpit or cabin.",
answer: 2},
{question: "Exfoliation in extruded metals is most likely caused by:",
choice1: "surface corrosion.",
choice2: "intergranular corrosion.",
choice3: "filiform corrosion.",
answer: 2},
{question: "If a bolt is to be torque loaded to 18ft.Ib using a 12-inch torque wrench fitted with a 6-inch straight extension, the indicated reading on the wrench dial should be:",
choice1: "10ft.Ib.",
choice2: "18ft.Ib.",
choice3: "12ft.Ib.",
answer: 3},
{question: "Which is the most useful source of information when beginning a fault finding task?",
choice1: "The aircrew member reporting the fault.",
choice2: "The aircraft maintenance manual.",
choice3: "The aircraft defect log.",
answer: 3},
{question: "If the maximum recommended torque has been reached when installing a castle nut, the split pin hole may be lined up by:",
choice1: "increasing the torque by a maximum of 10%.",
choice2: "replacing the nut with a different type and try again.",
choice3: "changing the washer or nut of the same type and try again.",
answer: 1},
{question: "The NDT method used to check an aluminium alloy part for surface cracks is:",
choice1: "dye penetrant.",
choice2: "ultrasonic.",
choice3: "x-ray.",
answer: 1},
{question: "To remove the ice accumulation on an aircraft and give it a long hold-over period:",
choice1: "a cold type 1 FPD de-ice followed by a heated and water mixed anti-ice would be used.",
choice2: "a cold type 2 FPD de-ice followed by a heated type 1 FPD and water mix anti-ice would be used.",
choice3: "a heated type 1 FPD de-ice followed by a cold type 2 FPD anti-ice would be used.",
answer: 3},
{question: "Which one of the following activities may be safety performed inside a hangar?",
choice1: "Engine ground running",
choice2: "Aircraft refuelling",
choice3: "Jacking",
answer: 3},
{question: "In the electrical cable feeding a power tool, the green wire would be:",
choice1: "phase.",
choice2: "neutral.",
choice3: "ground.",
answer: 3},
{question: "What is the preferred test equipment for measuring insulation resistance?",
choice1: "Bonding tester",
choice2: "Megger",
choice3: "Multimeter",
answer: 2},
{question: "When a replenishment cart contains both oxygen and nitrogen bottles, the nitrogen bottles should be:",
choice1: "significantly larger than oxygen bottles.",
choice2: "mounted in the opposite direction to oxygen bottles and have different hose connections.",
choice3: "greater in number and coloured black and white.",
answer: 2},
{question: "The spacing of clamps on a wire loom should be a t a distance that allows the 100mm section between the clamps to be deflected approximately:",
choice1: "1” (25mm) with normal hand pressure.",
choice2: "0.25” (6.36mm) with normal hand pressure.",
choice3: "0.5” (12.7mm) with normal hand pressure.",
answer: 3},
{question: "To be fully effective, the visual method of inspection requires a:",
choice1: "flashlight, mirror and magnifying glass.",
choice2: "flashlight, magnifying glass and cleaning cloth.",
choice3: "flashlight, mirror and cleaning cloth.",
answer: 3},
{question: "The title block of an engineering drawing is normally located at:",
choice1: "the top right hand corner.",
choice2: "the bottom right hand corner.",
choice3: "any convenient place on the drawing.",
answer: 2},
{question: "The inner details of a component on an engineering drawing can be shown by using:",
choice1: "an isometric view.",
choice2: "an oblique view.",
choice3: "a half section.",
answer: 3},
{question: "A 10 to 1 oscilloscope probe is used for measurements in:",
choice1: "low voltage circuits.",
choice2: "low impedance circuits.",
choice3: "high impedance circuits.",
answer: 3},
{question: "The most likely cause of bulging in a honeycomb structure is:",
choice1: "ram air entering an internal cavity.",
choice2: "expansion of the resin.",
choice3: "trapped water freezing and bulging the skin.",
answer: 3},
{question: "Other than trailing edge damage, lightning strikes can damage flight controls particularly in their:",
choice1: "hinge bearings.",
choice2: "internal ribs.",
choice3: "control rods",
answer: 1},
{question: "When tapping a blind hole, in which order would the following taps be used?",
choice1: "Plug, tapered and bottoming.",
choice2: "Tapered, plug and bottoming.",
choice3: "Bottoming, tapered and plug.",
answer: 2},
{question: "Which NDT method indicates the thickness of non-ferrous material when checking for defects?",
choice1: "Ultrasonic",
choice2: "Eddy current",
choice3: "Magnetic particle",
answer: 2},
{question: "A carbon dioxide extinguisher shall NOT be used on which one of the following classes of fire?",
choice1: "Class B - Flammable liquid",
choice2: "Class D - Combustible metals",
choice3: "Class C - Electrical equipment",
answer: 2},
];

//CONSTANTS
const CORRECT_BONUS = 1;
const MAX_QUESTIONS = 60; //For CAT B2, total number of questions is 52.

startGame = () => {
  questionCounter = 0;
  score = 0;
  //SAR66 each topic scores
  localStorage.setItem("maxMark", MAX_QUESTIONS);
  availableQuesions = [...questions];
  quizname.innerText = `M7: Maintenance`;
  getNewQuestion();
};

getNewQuestion = () => {
  if (availableQuesions.length === 0 || questionCounter >= MAX_QUESTIONS) {
    localStorage.setItem("mostRecentScore", score);
    //Generating the topic results
    //go to the end page
    return window.location.assign("../end.html");
  }
  questionCounter++;
  progressText.innerText = `Question ${questionCounter}/${MAX_QUESTIONS}`;
  //Update the progress bar
  progressBarFull.style.width = `${(questionCounter / MAX_QUESTIONS) * 100}%`;

  const questionIndex = Math.floor(Math.random() * availableQuesions.length);
  currentQuestion = availableQuesions[questionIndex];
  question.innerText = currentQuestion.question;

  choices.forEach(choice => {
    const number = choice.dataset["number"];
    choice.innerText = currentQuestion["choice" + number];
  });

  availableQuesions.splice(questionIndex, 1);
  acceptingAnswers = true;
};

choices.forEach(choice => {
  choice.addEventListener("click", e => {
    if (!acceptingAnswers) return;

    acceptingAnswers = false;
    const selectedChoice = e.target;
    const selectedAnswer = selectedChoice.dataset["number"];

    const classToApply = selectedAnswer == currentQuestion.answer ? "correct" : "incorrect";

    if (classToApply === "correct") {incrementScore(CORRECT_BONUS);};

    selectedChoice.parentElement.classList.add(classToApply);

    setTimeout(() => {
      selectedChoice.parentElement.classList.remove(classToApply);
      getNewQuestion();
    }, 1000);
  });
});

incrementScore = num => {
  score += num;
  scoreText.innerText = score;
};

startGame();
